/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: ['home',
                    'whats-new',
                    {
                      type: 'category',
                      label: 'About Me',
                      link: {type: 'doc', id: 'about-me'},
                      items: [{ type: 'autogenerated', dirName: 'about-me' }]
                    },
                    {
                      type: 'category',
                      label: 'Life, the Universe, and Everything',
                      link: {type: 'doc', id: 'life-universe-everything'},
                      items: [{ type: 'autogenerated', dirName: 'life-universe-everything' }]
                    },
                    {
                      type: 'category',
                      label: 'Things I\'ve Made',
                      link: {type: 'doc', id: 'things-made'},
                      items: [{ type: 'autogenerated', dirName: 'things-made' }]
                    },
                    {
                      type: 'category',
                      label: 'Resource Library',
                      link: {type: 'doc', id: 'resources'},
                      items: [{ type: 'autogenerated', dirName: 'resources' }]
                    },
                  ],
  guides: [{ type: 'autogenerated', dirName: 'guides' }]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
